### ISSUE TITLE
Fix update logic for wellbore

### ISSUE THREAD

**Issue by cherrera2001** [hashmapinc/Drillflow#211]
Currently create / read / delete works against DOT for wellbore but update fails with resource not found...

**Comment by randypitcherii** [comment]
I implemented this in a one line HOTFIX.

The issue is that drilltest did not require the `wellUid` querystring param when updating a wellbore object, but DoT does require it.

I did a simple if check on the type and added the querystring param for wellbore types before executing the REST call. Things work as they should now.
