### ISSUE TITLE
Coordinate Scope Review and Prioritization 

### ISSUE THREAD

**Issue by niaalex** [hashmapinc/Drillflow#371]
Team will work to Coordinate Scope Review and manage the Prioritization c/o Fluid report, Unit Conversion, Messages, etc.....

Once PCR is approved the team will address the ask from their side c/o  prioritization of fluids report and units conversion after log. Though they didn't specify which of those was the first priority. I suggested fluidsreport since its a static object, but that depends on their API implementation being ready, so based on their timing, units conversion might be first anyway. The need here is for the team to create the necessary cards and structure to represent thess objects in the project and then coordinate their planning as part of sprint planning.

Scope discussion TBD to cover the scope and priority.

**Comment by niaalex** [comment]
@cherrera2001  and Mike (don't see his @ in GitHub) lets be sure to cover this item in order to have an update for the client team.

**Comment by niaalex** [comment]
@cherrera2001 this is one of the things we said we would cover also

**Comment by niaalex** [comment]
@Mike-d-s this is one of the things we said we would cover also

**Comment by niaalex** [comment]
@cherrera2001 @Mike-d-s can you see this msx?
this is one of the things we said we would cover also

**Comment by cherrera2001** [comment]
Yes prioritize fluids report

**Comment by Mike-d-s** [comment]
The ask from their side was to prioritize fluidsreport and units conversion after log.  Though they didn't specify which of those was the first priority.  I suggested fluidsreport since its a static object, but that depends on their API implementation being ready, so based on their timing, units conversion might be first anyway.  The need here is for the team to create the necessary cards and structure to represent thess objects in the project and then coordinate their planning as part of sprint planning.

**Comment by niaalex** [comment]
Complete
