### ISSUE TITLE
QA: Certification Tests:Soap UI Cert Tests Trajectory

### ISSUE THREAD

**Issue by TessForGithub2** [hashmapinc/Drillflow#403]
Shehzad needs a chance to review the tests to understand what they are doing similar to what happened with Sukhendu & Theresa with Logs on 4/26. This is anticipated to happen with Mike today (4/26).

**Comment by niaalex** [comment]
@Mike-d-s 
@shehzadsidi will further review be required to cover the scope and planned ETA for this item?

**Comment by TessForGithub2** [comment]
Priority was changed; I worked on the new Traj Certification Tests. ETA on the new ones is 5/1; so the ETA on these existing tests will be 5/6 pending review by Shehzad as to the difficulty.

**Comment by niaalex** [comment]
@shehzadsidi Python script should be followed for this. Alert me if there is an issue.

**Comment by shehzadsidi** [comment]
Completed writing Test32, and successfully validated, pending Mike's validation/feedback.  I will work on the next one Monday so that will have at least couple to show in the demo.  Goal is to show the good progress.

**Comment by shehzadsidi** [comment]
I am on track to complete the Trajectory test cases by Friday (5/10).  There are still issues with the API which Schlumberger needs to address.

**Comment by niaalex** [comment]
@Shehzad

C/o issues with the API which Schlumberger needs to address.

Who owns the fix?  Where can I track this?  Was there an alert on the SLB Slack channel ??

**Comment by shehzadsidi** [comment]
Putting the details here for the issues that Schlumberger need to address:
all details that need to be addressed by Schlumberger in the APIs are mentioned in details in the following google document tracker:
https://docs.google.com/spreadsheets/d/1czJl7M9nIJJBiDoRpRu8sxO1eNQRRZH3Ctovy6jCju8/edit#gid=1634712486

**Comment by niaalex** [comment]
noted/thank you for the update Shehzad

**Comment by shehzadsidi** [comment]
Done updating/validating/creating all Trajectory Testcases and updated the document tracker as well.  There are several issues with the WITSML API which is preventing the test cases from executing successfully as expected.  Would like to request few mins of Mike's time to review.  Here is the update:

Many test cases are blocked due to the Schlumberger WITSML API not behaving as expected.  The details are as follows:

1. Add Trajectory and retrieve the added trajectory, objectGrowing is true.  DrillOps behavior for objectGrowing state should be false on add to store.  Should only be true after a defined append action 

2. Get trajectory, objectGrowing state query returns all objects. All Trjectory objects returned instead of one Trajectory regardless of the objectGrowing status (true or false)

3 Get trajectory optionsin returnElements = header-only, not currently supported for Trajectory

4. Get trajectory using standard query (SQ-012) with Well 1 uid, Wellbore1 uid, and Trajectory1 uid, optionsin returnElements=data-only, not currently supported

5. Get trajectory using standard query (SQ-012) with Well 1 uid, Wellbore1 uid, and Trajectory1 uid, optionsin returnElements= station-location-only, not currently supported

**Comment by niaalex** [comment]
Thank you for the update Shehzad

 

Let’s communicate these issues to the SLB team ASAP via email and slack notification BUT before you reach out to them, please be sure to review the updates from his morning in the SLB slack channel beforehand to be sure these issues are not associated.

**Comment by cherrera2001** [comment]
Out fo the following there are a few that are DrillOps bugs:

2,3,4,5 are all Drillflow….only 1 is a DrillOps Town problem.

**Comment by shehzadsidi** [comment]
Thanks so much Chris.  Can we book some time tomorrow so discuss, would really appreciate.

**Comment by cherrera2001** [comment]
Sure thing.

**Comment by shehzadsidi** [comment]
made great progress on Trajectory testcases.  The only outstanding issue is ObjectGrowing flag behavior issue on DoT APIs which Schlumberger has already been notified.  There are 3 test cases blocked due to this issue.  All others are complete and working as expected.

**Comment by shehzadsidi** [comment]
All Trajectory test cases are complete and working as expected.  The test cases are checked in the repository.  Closing the card.
