### ISSUE TITLE
DEV: Cannot query for StartDateTimeIndex and EndDateTimeIndex (Priority 1, ShowStopper)

### ISSUE THREAD

**Issue by shehzadsidi** [hashmapinc/Drillflow#617]
The DrillFlow should be able to handle the null case scenario for StartDateTimeIndex and EndDateTimeIndex during the merge when conversion from JSON to XML.  This is also true for all other null elements scenarios (including GrowingObject)

<?xml version="1.0" encoding="UTF-8"?>
<logs xmlns="http://www.witsml.org/schemas/1series"     
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:schemaLocation="http://www.witsml.org/schemas/1series  ../xsd_schemas/obj_log.xsd" 
    version="1.4.1.1">
    <log uidWell="HM_manual-testing1" uidWellbore="44f7929b-ea22-425c-975b-b3cb44279e75" uid="Log-DEF-Time3">
        <nameWell></nameWell>
        <nameWellbore></nameWellbore>
        <name></name>
        <serviceCompany></serviceCompany>
        <runNumber></runNumber>
        <creationDate></creationDate>
        <description></description>
        <indexType></indexType>
        <startIndex uom=""></startIndex>
        <endIndex uom=""></endIndex>
        <startDateTimeIndex></startDateTimeIndex>
        <endDateTimeIndex></endDateTimeIndex>
        <stepIncrement uom=""></stepIncrement>
        <direction></direction>
        <indexCurve></indexCurve>
        <nullValue></nullValue>
        <logParam uid="" index="" name="" uom="" description=""></logParam>
        <commonData>
            <dTimCreation></dTimCreation>
            <dTimLastChange></dTimLastChange>
            <itemState></itemState>
            <comments></comments>
        </commonData>
    </log>
</logs>

**Comment by TessForGithub2** [comment]
UPDATE: Chris' feedback on this --

For query there are 2 cases, the element exists with no filter criteria, the element exists without filter criteria, the element does not exist. This means 3 things:
1) if element exists with data, it means “use this value to filter for the data” and return it
2) if element exists without data, it means “return this value to me”
3) if element does not exist, it means “do not return this data”

So this RTC error happens when an element exists without data (specifically, StartDateTimeIndex and EndDateTimeIndex was mentioned to Chris, but this potentially exists with any element without data; see NOTE below).

To fix date/timestamps, the fix is to treat them as Strings by modifying the witsml objects library --

"Because it is an XML Gregorian Calendar [the null is removed, so ] the other option is treat it as a String. Modify the witsml objects library and just treat it like that; then the merge will still return it.
I suggest doing that (treat date/timestamp as Strings as it is done in well and wellbore for dates).
Dates as xmlgregoriancalendars are a super pain to work with."

PLEASE NOTE: This is also true for all other null element scenarios (including GrowingObject). Once Shehzad has the full test scenarios on SOAP (from RTC which first uncovered this), we can check where else in the codebase we have this issue with null elements.

**Comment by TessForGithub2** [comment]
UPDATE: ANY Java object that does not support null needs this same fix (so, Boolean, for example).

**Comment by niaalex** [comment]
This issue is resolved.
