### ISSUE TITLE
DEV: LOG: Update in Store fails with Data Only 

### ISSUE THREAD

**Issue by niaalex** [hashmapinc/Drillflow#627]
DEV: LOG: Update in Store fails with Data Only 

EPIC: Log Implementation 
This is the result of another fix.  The solution is known and @TessForGithub2  will enter it today.

ETA is 7/9/2019

**Comment by TessForGithub2** [comment]
The fix was not the result of another fix, as it turned out. The code needed to check for the existence of a JSON field before "getting" it. A simple 1-line fix that I did not release last night due to some confusion over an Add for Depth and an Update for Time that made it appear to be blocked by DoT. Released by Chris last night.

**Comment by TessForGithub2** [comment]
Update: Turns out, the code was not due to another fix but an issue I had resolved in Branch 395A but did not release due to all the activity surrounding Query. I was supposed to check for a JSON field's existence before attempting to get it. Resolved, tested, released.
