### ISSUE TITLE
DEV: LOG: UpdateInStore for Log Data (Depth and Time) does not work (ShowStopper, Priority 1)

### ISSUE THREAD

**Issue by shehzadsidi** [hashmapinc/Drillflow#628]

**Comment by shehzadsidi** [comment]
DEV: UpdateInStore for Log Data (Depth and Time) does not work (ShowStopper, Priority 1). Testcase attached.
[Error.txt](https://github.com/hashmapinc/Drillflow/files/3373765/Error.txt)
[Update Log Data (Depth).txt](https://github.com/hashmapinc/Drillflow/files/3373766/Update.Log.Data.Depth.txt)
[AddToStore Log (Depth).txt](https://github.com/hashmapinc/Drillflow/files/3373768/AddToStore.Log.Depth.txt)
[Add To Store Log (Time).txt](https://github.com/hashmapinc/Drillflow/files/3373807/Add.To.Store.Log.Time.txt)
[UpdateToStore Log (Time).txt](https://github.com/hashmapinc/Drillflow/files/3373808/UpdateToStore.Log.Time.txt)
[Error UpdateTo Store (Time).txt](https://github.com/hashmapinc/Drillflow/files/3373809/Error.UpdateTo.Store.Time.txt)

**Comment by TessForGithub2** [comment]
UPDATE: 

The bug in Drillflow has been identified and fixed for depth (and I will trace for time, but since it traverses the same code, I assume that time has been fixed also).

However, effective testing by QA is blocked because the DoT bug has been discovered where DoT deletes ALL channels after a channelset Update. This error has gone undetected this long because we usually update with channels directly after a channelset update. I will block the QA card, but close this one after I trace for time.

**Comment by TessForGithub2** [comment]
Update: I will release the code and then close this card tonight.

**Comment by TessForGithub2** [comment]
Update: 
Chris performed the same change that I had, and it is now working.

Additional Information:
It turned out that the AddToStore was Depth and the UpdateFromStore was Time; mixing the 2 allowed an update to the ChannelSet (setting it to Time and disassociating it from the Channels that were Depth; the Channels were not deleted). This is why the Data Post did not return an error; it simply did not have any Channels with which to associate the Data. Chris put in the fix I found yesterday, so it is now working.

It is unblocked (I will check that the card is unblocked now). Chris said that it was not a big deal on either side since it was an invalid test. Since we do not retain state (the one true record of the DB is on DoT side), there is no way we could have checked without performing a GET, which we will not be doing.
