### ISSUE TITLE
QA: Test the UpdateInStore Log Data Bug (Priority1, ShowStopper) #628

### ISSUE THREAD

**Issue by shehzadsidi** [hashmapinc/Drillflow#629]
QA: Test the UpdateInStore Log Data Bug (Priority1, ShowStopper) #628

**Comment by TessForGithub2** [comment]
UPDATE: The bug in just data (and channelset) for an UpdateInStore for LOG has been fixed. I have traced it through the codebase.

However, a subsequent Query check by QA will fail due to a DoT "bug" where the first REST call to Patch ChannelSet results in ALL channels being deleted. This has been communicated to Mike and the team via email; he will forward to SLB. The DEV card will be closed.

**Comment by TessForGithub2** [comment]
Update: The real issue was depth was being used for the Add while time was being used for the Update. Resolved, tested, and released.
